In [64]:
import os
import torch
import numpy as np
import random
from torch.utils.data import DataLoader, Dataset
import math

class SpeedDataset(Dataset):
    def __init__(self, directory, sequence_length=5, augment=True):
        self.data = []
        self.sequence_length = sequence_length
        self.num_classes = (105 - 30) // 10 + 1  # Speed classes from 30-39, ..., 100-105
        self.augment = augment  # Enable or disable augmentation
        self.preprocess_data(directory)
        self.normalize_features()

    def preprocess_data(self, directory):
        for filename in os.listdir(directory):
            if filename.endswith('.txt'):
                speed = float(filename.split('_')[-1].replace('.txt', ''))
                speed_class = 0 if speed < 30 else (int(speed) - 30) // 10
                filepath = os.path.join(directory, filename)
                with open(filepath, 'r') as file:
                    track_data = {}
                    for line in file:
                        points = line.strip().split(',')
                        if len(points) == 6:
                            frame, track_id, x1, y1, x2, y2 = map(float, line.strip().split(','))
                        if len(points) == 7:
                            frame,class_id, track_id, x1, y1, x2, y2 = map(float, line.strip().split(','))
                        if track_id not in track_data:
                            track_data[track_id] = []
                        track_data[track_id].append([x1, y1, x2, y2])

                    for track_id, frames in track_data.items():
                        if len(frames) >= self.sequence_length:
                            features = self.extract_features(frames)
                            overlap = 5  # Overlap for sequence extraction
                            for start_idx in range(0, len(features) - self.sequence_length + 1, self.sequence_length - overlap):
                                end_idx = start_idx + self.sequence_length
                                sequence = features[start_idx:end_idx]
                                self.data.append((sequence, speed_class))

    def extract_features(self, frames):
        features = []
        for i in range(1, len(frames)):
            current_frame = frames[i]
            previous_frame = frames[i-1]
            features.append(self.compute_frame_features(current_frame, previous_frame))
        return features

    def compute_frame_features(self, current_frame, previous_frame):
        x1, y1, x2, y2 = current_frame
        px1, py1, px2, py2 = previous_frame

        width, height = x2 - x1, y2 - y1
        p_width, p_height = px2 - px1, py2 - py1

        x2_change = x2 - px2
        y2_change = y2 - py2
        x1_change = x1 - px1
        y1_change = y1 - py1

        width_change = width - p_width
        height_change = height - p_height
        area_change = (width * height) - (p_width * p_height)
        perimeter_change = (2 * (width + height)) - (2 * (p_width + p_height))

        center_x, center_y = (x1 + x2) / 2, (y1 + y2) / 2
        p_center_x, p_center_y = (px1 + px2) / 2, (py1 + py2) / 2
        center_x_change = center_x - p_center_x
        center_y_change = center_y - p_center_y
        distance_moved = math.sqrt(center_x_change ** 2 + center_y_change ** 2)

        velocity = distance_moved/0.03  # Assuming constant frame rate
        p_velocity = (math.sqrt((px2 - px1) ** 2 + (py2 - py1) ** 2))/0.03
        acceleration = abs(velocity - p_velocity)

        feature_vector = [x1_change, y1_change, x2_change, y2_change,
                          center_x_change, center_y_change, distance_moved, velocity, acceleration]
        return feature_vector

    def normalize_features(self):
        all_features = [feature for sequence, _ in self.data for feature in sequence]
        all_features = np.array(all_features)
        self.mean = np.mean(all_features, axis=0)
        self.std = np.std(all_features, axis=0)
        for i, (sequence, speed_class) in enumerate(self.data):
            normalized_sequence = (sequence - self.mean) / (self.std)
            self.data[i] = (normalized_sequence, speed_class)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        inputs, output = self.data[idx]
        if self.augment:
            inputs = self.apply_augmentation(inputs)
        return torch.tensor(inputs, dtype=torch.float32), torch.tensor(output, dtype=torch.long)

    def apply_augmentation(self, inputs):
        if random.random() > 0.5:
            inputs = self.add_noise(inputs)
        if random.random() > 0.5:
            inputs = self.time_shift(inputs, shift=random.choice([-1, 1]))
        if random.random() > 0.5:
            inputs = self.scale_features(inputs, scale=random.uniform(0.9, 1.1))
        if random.random() > 0.5:
            inputs = self.mirror_features(inputs)
        return inputs

    def add_noise(self, features, noise_level=0.05):
        noise = np.random.normal(0, noise_level, features.shape)
        return features + noise

    def time_shift(self, features, shift=1):
        if shift > 0:
            return np.vstack([np.zeros((shift, features.shape[1])), features[:-shift]])
        elif shift < 0:
            return np.vstack([features[-shift:], np.zeros((-shift, features.shape[1]))])
        return features

    def scale_features(self, features, scale=1.1):
        return features * scale

    def mirror_features(self, features):
        features_copy = features.copy()
        features_copy[:, [0, 2]] = -features_copy[:, [0, 2]]  # Assume these indices are the x-coordinates
        return features_copy


In [74]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import torch.nn as nn
import torch.nn.functional as F

class Attention(nn.Module):
    def __init__(self, hidden_dim):
        super(Attention, self).__init__()
        self.hidden_dim = hidden_dim
        self.linear = nn.Linear(hidden_dim, 1)

    def forward(self, x):
        weights = F.softmax(self.linear(x), dim=1)
        weighted_output = weights * x
        return weighted_output.sum(1), weights

class SpeedPredictor(nn.Module):
    def __init__(self, sequence_length, feature_size, embedding_dim, hidden_dim, output_size):
        super(SpeedPredictor, self).__init__()
        self.conv1 = nn.Conv1d(in_channels=feature_size, out_channels=embedding_dim, kernel_size=1)
        self.lstm = nn.GRU(embedding_dim, hidden_dim, batch_first=True, num_layers=3)
        self.dropout = nn.Dropout(p=0.5)
        self.fc2 = nn.Linear(32, output_size)  
        self.relu = nn.ReLU()
        self.conv2 = nn.Conv1d(in_channels=hidden_dim, out_channels=128, kernel_size=1)
        self.attention = Attention(hidden_dim)
        self.fc1 = nn.Linear(128, 32)

    def forward(self, x):
        x = x.permute(0, 2, 1)  
        x = self.conv1(x)
        x = x.permute(0, 2, 1)  
        x, _ = self.lstm(x)
        x = self.dropout(x)
        x, attn_weights = self.attention(x)
        x = x.unsqueeze(2)
        x = self.conv2(x)
        x = x.squeeze(2)
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x  
def init_weights(m):
    if type(m) == nn.LSTM:
        torch.nn.init.xavier_uniform_(m.weight_ih_l0)
        torch.nn.init.orthogonal_(m.weight_hh_l0)
    if type(m) == nn.Linear:
        torch.nn.init.kaiming_normal_(m.weight)

In [75]:
import torch

# Check for CUDA
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)


Using device: cuda


In [76]:

def train(model, train_loader, test_loader, criterion, optimizer, scheduler, epochs):
    for epoch in range(epochs):
        model.train()
        Train_total_loss = 0
        correct_train = 0
        total_train = 0

        for inputs, targets in train_loader:
            inputs, targets = inputs.to(device), targets.to(device)  # Ensure inputs and targets are on the same device as model
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            loss.backward()
            optimizer.step()  # First, update the parameters with the current learning rate
            
            Train_total_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            correct_train += (predicted == targets).sum().item()
            total_train += targets.size(0)
        
        scheduler.step()  # After optimizer updates, adjust the learning rate

        if epoch % 10 == 0 or epoch == epochs - 1:
            model.eval()
            correct_test = 0
            total_test = 0
            total_loss = 0
            with torch.no_grad():
                for inputs, targets in test_loader:
                    inputs, targets = inputs.to(device), targets.to(device)
                    outputs = model(inputs)
                    loss = criterion(outputs, targets)
                    total_loss += loss.item()
                    _, predicted = torch.max(outputs.data, 1)
                    correct_test += (predicted == targets).sum().item()
                    total_test += targets.size(0)
                    
            train_accuracy = 100 * correct_train / total_train
            test_accuracy = 100 * correct_test / total_test
            print(f'Epoch {epoch+1}: Train Loss: {Train_total_loss / len(train_loader)} Test Loss: {total_loss / len(test_loader)}, '
                  f'Train Accuracy: {train_accuracy:.2f}%, Test Accuracy: {test_accuracy:.2f}%')


In [78]:
import torch
from torch.utils.data import DataLoader, random_split
from torch.optim import SGD, Adam
from torch.optim.lr_scheduler import ExponentialLR


train_dataset = SpeedDataset('outputs', sequence_length=10,augment=True)
test_dataset = SpeedDataset('test_outputs', sequence_length=10,augment=False)
print(len(train_dataset))
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=10, shuffle=False)
max_classes = train_dataset.num_classes
model = SpeedPredictor(sequence_length=10, feature_size=9, embedding_dim=64, hidden_dim=128, output_size=max_classes)
model.to(device)  
model.apply(init_weights)
criterion = nn.CrossEntropyLoss().to(device)  
optimizer = SGD(model.parameters(), lr=0.01)
scheduler = ExponentialLR(optimizer, gamma=0.9999) 
train(model, train_loader, test_loader, criterion, optimizer, scheduler, epochs=400)


7822
Epoch 1: Train Loss: 2.0273018150913473 Test Loss: 2.009911710396409, Train Accuracy: 17.02%, Test Accuracy: 19.30%
Epoch 11: Train Loss: 1.6482640344269421 Test Loss: 1.713574007153511, Train Accuracy: 28.78%, Test Accuracy: 24.53%
Epoch 21: Train Loss: 1.2991092978691567 Test Loss: 1.2255661434028298, Train Accuracy: 45.36%, Test Accuracy: 44.94%
Epoch 31: Train Loss: 1.2119855520676592 Test Loss: 1.0729550526011735, Train Accuracy: 48.02%, Test Accuracy: 54.43%
Epoch 41: Train Loss: 1.1810932808992813 Test Loss: 1.0240408451354597, Train Accuracy: 49.78%, Test Accuracy: 56.01%
Epoch 51: Train Loss: 1.1568956139136335 Test Loss: 1.0403678721631877, Train Accuracy: 50.75%, Test Accuracy: 55.85%
Epoch 61: Train Loss: 1.1347249242724204 Test Loss: 1.0268865655525587, Train Accuracy: 51.80%, Test Accuracy: 52.85%
Epoch 71: Train Loss: 1.1137098122616202 Test Loss: 1.0528860228369012, Train Accuracy: 51.18%, Test Accuracy: 54.43%
Epoch 81: Train Loss: 1.1160282020666161 Test Loss: 1.

In [82]:
from sklearn.metrics import confusion_matrix, classification_report
def print_confusion_matrix_and_report(all_targets, all_preds):
    print(confusion_matrix(all_targets, all_preds))
    print(classification_report(all_targets, all_preds, target_names=[f'Class {30 + i * 10}-{39 + i * 10}' for i in range(max(all_targets) + 1)]))


In [83]:
def evaluate(model, test_loader):
    model.eval()
    correct_test = 0
    total_test = 0
    all_preds = []
    all_targets = []
    with torch.no_grad():
        for inputs, targets in train_loader:
            inputs, targets = inputs.to(device), targets.to(device)  # Ensure inputs and targets are on the same device as model
            outputs = model(inputs)
            _, predicted = torch.max(outputs.data, 1)
            correct_test += (predicted == targets).sum().item()
            total_test += targets.size(0)
            all_preds.extend(predicted.cpu().numpy())
            all_targets.extend(targets.cpu().numpy())

    test_accuracy = 100 * correct_test / total_test
    print("Confusion Matrix and Classification Report:")
    print_confusion_matrix_and_report(all_targets, all_preds)
    return test_accuracy
evaluate(model, test_loader)  

Confusion Matrix and Classification Report:
[[899 260  24   2   2   1   0   0]
 [204 976 217  26  39   1   6   0]
 [ 15 318 728 131  87   3   8   0]
 [  4  78 337 474 228  16  17   0]
 [  0  14 107 132 603 130  51   0]
 [  2   5  32  31 201 333 129   0]
 [  0   0  11  11  84 117 466   8]
 [  0   0   1   2  17  23 187  24]]
               precision    recall  f1-score   support

  Class 30-39       0.80      0.76      0.78      1188
  Class 40-49       0.59      0.66      0.63      1469
  Class 50-59       0.50      0.56      0.53      1290
  Class 60-69       0.59      0.41      0.48      1154
  Class 70-79       0.48      0.58      0.52      1037
  Class 80-89       0.53      0.45      0.49       733
  Class 90-99       0.54      0.67      0.60       697
Class 100-109       0.75      0.09      0.17       254

     accuracy                           0.58      7822
    macro avg       0.60      0.52      0.52      7822
 weighted avg       0.59      0.58      0.57      7822



57.56839682945538

In [84]:
def evaluate(model, test_loader):
    model.eval()
    correct_test = 0
    total_test = 0
    all_preds = []
    all_targets = []
    with torch.no_grad():
        for inputs, targets in test_loader:
            inputs, targets = inputs.to(device), targets.to(device)  # Ensure inputs and targets are on the same device as model
            outputs = model(inputs)
            _, predicted = torch.max(outputs.data, 1)
            correct_test += (predicted == targets).sum().item()
            total_test += targets.size(0)
            all_preds.extend(predicted.cpu().numpy())
            all_targets.extend(targets.cpu().numpy())

    test_accuracy = 100 * correct_test / total_test
    print("Confusion Matrix and Classification Report:")
    print_confusion_matrix_and_report(all_targets, all_preds)
    return test_accuracy
evaluate(model, test_loader)  

Confusion Matrix and Classification Report:
[[82 14  0  0  0  0  0  0]
 [ 9 73 36  0  4  0  0  0]
 [ 1 25 61  4  5  0  0  0]
 [ 0  5 43 54 20  1  0  0]
 [ 0  0 12 13 44  1  0  0]
 [ 0  1  4  3 18 29 25  0]
 [ 0  0  0  0  0  0 12  1]
 [ 0  0  0  1  1  3 19  8]]
               precision    recall  f1-score   support

  Class 30-39       0.89      0.85      0.87        96
  Class 40-49       0.62      0.60      0.61       122
  Class 50-59       0.39      0.64      0.48        96
  Class 60-69       0.72      0.44      0.55       123
  Class 70-79       0.48      0.63      0.54        70
  Class 80-89       0.85      0.36      0.51        80
  Class 90-99       0.21      0.92      0.35        13
Class 100-109       0.89      0.25      0.39        32

     accuracy                           0.57       632
    macro avg       0.63      0.59      0.54       632
 weighted avg       0.66      0.57      0.58       632



57.436708860759495